model:
  input_len: 96       # encoder length
  pred_len: 96        # decoder prediction length

training:
  batch_size: 512
  epochs: 5        # reduced epochs per request
  lr: 1e-5

data:
  tensor_path: data/windows.pt